import { useStore } from "../GlobalState/useStore.js";

const setLanguageSection_KO = (language) => {
  if (!language) {
    console.error("Language is not defined");
    return;
  }

  if (typeof language !== "string") {
    console.error("Language must be a string");
    return;
  }

  useStore.setState({
    btnHelp: "도움말",
    fontSizeText: `글자 크기`,
    cardHeightText: `카드 높이`,
    btnNext: "계속",
    stepCompletedMessage: `이 단계를 완료하셨습니다. 화면 오른쪽 하단의 <b>파란색 "계속" 버튼</b>을 클릭하여 다음 단계로 이동하세요.`,
    screenOrientationText: `세로 방향을 사용해주세요!`,
    mobileTextSize: `텍스트`,
    mobileViewSize: `보기`,
    mobileModalButtonCancel: `취소`,
    preventMobileTitle: "모바일 접근 제한 제목",
    preventMobileMessage: "모바일 접근 제한 메시지",
    expandViewMessage: `아래의 보기 "+" 버튼을 눌러 보기 영역을 확장하고 이 메시지를 숨기세요.`,
    consentTitleBarText: `연구 동의서`,
    consentText: `귀하는 [기관 또는 조직]의 [주연구자 이름]이 수행하는 연구에 참여하도록 초대되었습니다. 참여를 결정하기 전에 연구가 수행되는 이유와 무엇을 포함하는지 이해하는 것이 중요합니다. 다음 정보를 주의 깊게 읽어주시기 바랍니다. 궁금한 점이 있으시면 연구팀에 자유롭게 연락하시기 바랍니다.<br /><br /><b>연구 목적</b><br />본 연구의 목적은 [목적을 간략히 설명, 예: 새로운 교수법이 학생 성과에 미치는 영향을 이해하는 것]입니다. 이 연구는 [연구의 더 넓은 의미나 목표를 언급]에 대한 통찰력을 얻는 데 도움이 될 것입니다. <br /><br /><b>연구 절차</b><br />참여에 동의하시면, 귀하는 [포함된 절차, 참여자가 할 일, 소요 시간, 빈도를 설명]을 요청받게 됩니다. 예를 들어, 일련의 진술문을 평가하고 분류한 다음 분류에 대해 성찰하도록 요청받게 됩니다. 또한 마지막에 짧은 설문지가 있습니다. 연구는 약 [기간, 예: 45분]이 소요됩니다. <br /><br /><b>혜택</b><br />참여에 대한 직접적인 혜택은 없을 수 있지만, 이 연구에서 수집된 정보는 [잠재적 혜택 설명, 예: 교육 방법 개선, 과학 지식에 기여 등]에 도움이 될 수 있습니다. 또한 [해당되는 경우 개인적 혜택 설명]에 대한 개인적 통찰력을 얻을 수 있습니다.<br /><br /><b>비밀 보장</b><br />본 연구에서 수집된 모든 정보는 엄격히 비밀로 유지됩니다. 데이터는 안전하게 저장되며 연구팀만 접근할 수 있습니다. 귀하의 신원은 본 연구의 결과로 작성되는 어떤 보고서나 출판물에서도 공개되지 않습니다. [데이터가 어떻게 익명화, 암호화 또는 안전하게 저장되는지 설명].<br /><br /><b>자발적 참여</b><br />본 연구 참여는 전적으로 자발적입니다. 귀하는 참여를 거부하거나 언제든지 철회할 수 있으며, 불이익이나 귀하가 받을 자격이 있는 혜택의 손실 없이 가능합니다. 철회를 결정하시면, 웹페이지를 닫으시면 그 시점까지 수집된 모든 데이터가 삭제됩니다.<br /><br /><b>동의</b><br />이 페이지 하단의 "동의" 버튼을 클릭함으로써, 귀하는 제공된 정보를 읽고 이해했으며, 본 연구 참여에 동의함을 나타냅니다. 본 연구에 대해 질문이 있으시면 [주연구자 이름 및 연락처]로 연락주시기 바랍니다.`,
    consentHelpModalHead: `연락처 정보`,
    consentHelpModalText: `이 대학교 연구 프로젝트에 참여해 주셔서 감사합니다. 전화(1-555-867-5309) 또는 이메일 researchTeam@myMail.com으로 연구팀에 연락하실 수 있습니다`,
    btnHelpConsent: `연락처 정보`,
    btnNextConsent: `동의 및 계속`,
    loginWelcomeText: `<center></center><h3>환영합니다!</h3></center><br/> Q 방법론 연구 프로젝트에 참여해 주셔서 감사합니다. <br/>절차를 시작하려면 아래 양식을 사용하여 <b>로그인</b>해 주세요. `,
    loginHeaderText: `로그인`,
    loginPartIdText: `이름 또는 참여자 ID를 입력해 주세요`,
    accessCodeText: `액세스 코드`,
    accessInputText: "이 설문조사의 액세스 코드를 입력해 주세요.",
    partIdWarning: `유효하지 않은 이름 또는 ID`,
    accessCodeWarning: `액세스 코드가 유효하지 않습니다`,
    loginSubmitButtonText: `제출`,
    landingHead: `대학교 연구 프로젝트`,
    welcomeText: `<h2>Quince 데모 프로젝트 - 교실에서의 iPad 사용.</h2><br/><br/><p>이 연구 프로젝트를 도와주셔서 감사합니다</p><br/>`,
    landingHelpModalHead: `환영합니다!`,
    landingHelpModalText: `이 대학교 연구 프로젝트에 참여해 주셔서 감사합니다. 다음 단계로 이동하려면 화면 오른쪽 하단의 "<b>계속</b>" 버튼을 클릭하세요.`,
    btnNextLanding: `계속`,
    btnHelpLanding: `도움말`,
    mobileWelcomeText: `<h2>Quince 데모 프로젝트 - 교실에서의 iPad 사용.</h2><br/><br/><p>이 연구 프로젝트를 도와주셔서 감사합니다!</p><br/>`,
    logInFirst: "먼저 로그인 절차를 완료해 주세요.",
    titleBarText: `예비 분류`,
    presortAgreement: `동의 (3)`,
    presortNeutral: `강한 의견 없음 (2)`,
    presortDisagreement: `동의하지 않음 (1)`,
    presortStatements: `진술문`,
    presortModalHead: `1단계 / 4단계`,
    presortModalText: `다음 진술문을 주의 깊게 읽고 세 더미로 나누세요: 동의하지 않는 경향이 있는 진술문 더미, 동의하는 경향이 있는 카드 더미, 그리고 나머지 더미. 나중에 변경할 수 있습니다.<br/><br/>이 지침을 다시 읽으려면 왼쪽 하단의 도움말 버튼을 클릭하세요.<br/>`,
    presortPreventNavModalHead: `탐색 비활성화`,
    presortPreventNavModalText: `다음 단계로 이동하기 전에 예비 분류를 완료해 주세요.`,
    presortFinishedModalHead: `예비 분류 완료`,
    presortFinishedModalText: `이 단계를 완료하셨습니다. 다음 단계로 이동하려면 페이지 오른쪽 하단의 "계속" 버튼을 클릭하세요.`,
    presortOnPageInstructions: `<div style="font-size: 24px">카드를 클릭하고 드래그하거나 "1", "2" 또는 "3" 키를 눌러 진술문을 분류하세요.</div>`,
    presortImageSortInstructions: `이미지를 확대하려면 마우스 포인터를 그 위에 올리고 더블클릭하세요. <br/><br/> 이미지를 비교하려면 키보드의 <b><i>Shift</i></b> 키를 <u>누른 상태로 유지</u>한 다음 마우스로 두 개의 이미지를 더블클릭하세요.`,
    mobilePresortConditionsOfInstruction: `수업에서 iPad를 사용한 경험에 따라 진술문을 평가하세요`,
    mobilePresortCompletedLabel: `완료된 평가`,
    mobilePresortAssignLeft: `내 관점과 다름`,
    mobilePresortAssignRight: `내 관점과 유사함`,
    mobilePresortRedoModalHead: `진술문 재평가`,
    mobilePresortRedoModalText: `적절한 아이콘을 클릭하세요`,
    mobilePresortRedoModalConfirmButton: `확인`,
    mobilePresortEvaluationsComplete: `<div><b>모든 진술문 평가 완료.</b> <br /><br />평가를 확인하기 위해 진술문을 검토해 주세요.  <br /><br /><div>`,
    mobilePresortHelpModalHead: `1단계 / 5단계<br />진술문 평가`,
    mobilePresortHelpModalText: `각 진술문에 값을 할당하려면 적절한 버튼을 누르세요. <br /><br /> 진술문이 <b>귀하의 관점과 유사하다</b>고 느끼시면 녹색 "+" 버튼을 누르세요.<br /><br /> 진술문이 <b>귀하의 관점과 다르다</b>고 느끼시면 빨간색 "-" 버튼을 누르세요. <br /><br />확실하지 않으면 "?" 버튼을 누르세요. <br /><br /> 이 설문조사에는 <b>33개의 진술문</b>이 있습니다. <br /><br /> 평가를 <b>변경</b>하려면 진술문 옆의 <b>다시하기 아이콘</b>을 누르세요.`,
    mobilePresortFinishedModalHead: `1단계 / 5단계<br />진술문 평가`,
    mobilePresortFinishedModalText: `평가 과정이 완료되었습니다. <br/><br/> 평가를 확인하기 위해 <b>진술문을 검토</b>해 주세요.  <br /><br />변경하려면 진술문 왼쪽의 "다시하기" 아이콘을 누르세요.<br /><br />모든 평가에 만족하시면 오른쪽 하단의 <b>탐색 버튼</b>을 누르세요.`,
    mobilePresortProcessCompleteMessage: `평가 과정이 완료되었습니다. <br/><br/> 다음 단계로 이동하려면 오른쪽 하단의 탐색 버튼을 클릭하세요.`,
    mobilePresortPreventNavModalHead: `탐색 비활성화`,
    mobilePresortPreventNavModalText: `다음 단계로 이동하기 전에 평가를 완료해 주세요.`,
    thinPageTitle: `평가 정제`,
    thinPageSubmitButton: `제출`,
    numStatementsToSelect: `선택할 진술문 수`,
    currentlySelectedNumber: `현재 선택된 진술문 수`,
    thinningPreventNavModalHead: `탐색 비활성화`,
    thinningPreventNavModalText: `다음 단계로 이동하기 전에 정제 과정을 완료해 주세요.`,
    thinningHelpModalHead: `평가 정제`,
    thinningHelpModalText: `이전 단계에서 평가한 진술문을 다시 살펴보세요. 귀하의 관점을 가장 잘 표현한다고 느끼는 진술문을 선택하세요.`,
    thinningConfirmModalHead: `선택 미완료`,
    thinningConfirmModalText: `필요한 수의 진술문을 선택해 주세요.`,
    initialInstructionPart1: `아래는 이전 단계에서 긍정적으로 평가한 진술문입니다. 이제 <b>가장 동의하는</b> 진술문의 수를 선택하세요.<br /><br />`,
    initialInstructionPart2: `다음으로, 귀하의 관점에 가장 가까운 진술문을 계속 선택하세요`,
    initialInstructionPart3: `주황색 "제출" 버튼을 클릭하면 다른 진술문 세트가 화면에 나타납니다.`,
    initialInstructionPartNeg1: `아래는 이전 단계에서 긍정적으로 평가한 진술문입니다. 이제 <mark><b>귀하의 관점과 가장 다른</b></mark> 진술문을 선택하세요.`,
    initialInstructionPartNeg2: `다음으로, 귀하의 관점과 <mark>가장 다른</mark> 진술문을 계속 선택하세요.`,
    finalInstructions: `정제 과정이 완료되었습니다. 다음 단계로 이동하려면 오른쪽 하단의 탐색 버튼을 클릭하세요.`,
    moveTopMobileHead: `이동 확인`,
    moveAllTopMobileText: `선택한 모든 진술문을 목록 상단으로 이동하시겠습니까?`,
    moveTopMobileButtonOK: `예`,
    mobileModalButtonCancel: `취소`,
    mobileThinConditionsOfInstruction: `평가 정제`,
    mobileThinSubmitButtonText: `제출`,
    mobileThinSelectedText: `선택됨`,
    mobileThinHelpModalHead: `2단계 / 5단계<br/>정제 과정`,
    mobileThinHelpModalText: `이 단계에서는 평가한 <b>진술문을 검토</b>하고 귀하의 관점과 가장 유사하거나 가장 다른 진술문을 선택하도록 요청받습니다.<br/><br/>모든 진술문을 보려면 <b>아래로 스크롤</b>해야 할 수 있습니다.<br/><br/><b>진술문을 선택</b>하려면 진술문 컨테이너를 누르세요. 진술문의 색상이 노란색으로 변경됩니다.<br/><br/><b>올바른 수</b>의 진술문을 선택하면 "제출" 버튼이 <b>파란색</b>으로 변경됩니다. <br/><br/>진술문을 더 쉽게 비교하기 위해 진술문 오른쪽 또는 왼쪽에 있는 위아래 화살표를 눌러 <b>순서를 변경</b>할 수 있습니다.<br/><br/>진술문 오른쪽의 화살표를 <b>길게 누르면</b>(약 1초) 선택한 진술문 <b>그룹을 이동</b>하여 목록 상단으로 이동할 수도 있습니다.`,
    mobileThinPreventNavModalHead: `탐색 비활성화`,
    mobileThinPreventNavModalText: `다음 페이지로 이동하기 전에 정제 과정을 완료해 주세요.`,
    mobileThinProcessCompleteMessage: `정제 과정이 완료되었습니다. <br/><br/> 다음 단계로 이동하려면 오른쪽 하단의 탐색 버튼을 클릭하세요.`,
    mobileGuidanceModalRight1Header: `2단계 / 5단계<br/> 정제 과정`,
    mobileGuidanceModalRight1Text: `이 단계에는 여러 단계가 있습니다. <br/><br/>1단계. <b>긍정적으로</b> 평가한 모든 진술문을 살펴보고 <b>귀하의 관점에 가장 가까운</b> 진술문을 선택하세요.<br/><br/>모든 진술문을 보려면 <b>아래로 스크롤</b>해야 할 수 있습니다.`,
    mobileGuidanceModalRight2Header: `2단계 / 5단계<br/> 정제 과정`,
    mobileGuidanceModalRight2Text: `다음으로, <b>긍정적으로</b> 평가한 나머지 진술문을 다시 살펴보고 <b>귀하의 관점에 가장 가까운</b> <b>다음 세트</b>의 진술문을 선택하세요.`,
    mobileGuidanceModalLeft1Header: `2단계 / 5단계<br/> 정제 과정`,
    mobileGuidanceModalLeft1Text: `2단계. 다음으로, 부정적으로 평가한 모든 진술문을 살펴보고 귀하의 관점과 <b>가장 다른</b> 진술문을 <b>선택</b>하세요.<br/><br/>모든 진술문을 보려면 <b>아래로 스크롤</b>해야 할 수 있습니다.`,
    mobileGuidanceModalLeft2Header: `2단계 / 5단계<br/> 정제 과정`,
    mobileGuidanceModalLeft2Text: `다음으로, <b>부정적으로</b> 평가한 나머지 진술문을 다시 살펴보고 <b>귀하의 관점과 가장 다른</b> <b>다음 세트</b>의 진술문을 <b>선택</b>하세요.`,
    mobileThinScrollBottomModalHead: `확인 비활성화`,
    mobileThinScrollBottomModalText: `선택을 확인하기 전에 맨 아래로 스크롤하여 모든 진술문을 검토해 주세요.`,
    sortHelpModalHead: `3단계 / 5단계`,
    sortHelpModalText: `이 단계에서는 페이지 상단의 연구자 지침과 귀하의 관점에 따라 진술문 카드를 적절한 열로 클릭하고 드래그하세요. <br/>`,
    sortAgreement: `동의`,
    sortDisagreement: `동의하지 않음`,
    condOfInst: `이번 학기 iPad 사용 경험에 따라 카드를 분류하세요`,
    sortingCompleteModalHead: `분류 완료`,
    sortingCompleteModalText: `초기 분류를 완료하셨습니다. 잠시 시간을 내어 카드 배치를 확인해 주세요.<br/><br/>배치에 만족하시면, 화면 오른쪽 하단의 <b>파란색 "계속" 버튼</b>을 클릭하여 다음 단계로 이동하세요.`,
    sortPreventNavModalHead: `탐색 비활성화`,
    sortPreventNavModalText: `다음 단계로 이동하기 전에 그리드 분류를 완료해 주세요.`,
    sortOverloadedColumnModalHead: `탐색 비활성화`,
    sortOverloadedColumnModalText: `열 중 하나에 너무 많은 카드가 있습니다(주황색으로 윤곽선이 표시되고 점선 테두리가 있습니다). 모든 열이 올바른 수를 갖도록 카드 배치를 조정해 주세요.`,
    mobileSortSwapModalHead: `진술문 순위를 교환하시겠습니까?`,
    mobileSortSwapModalSuccessMessage: "진술문의 위치가 성공적으로 교환되었습니다.",
    mobileSortSwapModalText: `교환하려면 "확인"을 클릭하세요.`,
    mobileSortSwapModalConfirmButton: `교환`,
    mobileSortConditionsOfInstruction: `수업에서 iPad를 사용한 경험에 따라 진술문의 순위를 매기세요`,
    mobileSortHelpModalHead: `3단계 / 5단계<br/> 최종 진술문 순위`,
    mobileSortHelpModalText: `진술문은 귀하의 이전 평가를 기반으로 순위가 매겨졌습니다.<br/><br/> 귀하의 관점에 가장 가까운 진술문은 목록 상단에 있어야 합니다. 귀하의 관점과 가장 먼 진술문은 목록 하단에 있어야 합니다.<br/><br/>모든 진술문을 보려면 <b>아래로 스크롤</b>해야 합니다.<br/><br/><b>순위를 검토</b>하고 순서가 <b>귀하의 관점을 정확히 반영</b>하도록 진술문 순위에 필요한 변경을 수행하세요. <br/><br/><mark>이것은 설문조사의 가장 중요한 단계이므로 진술문 순위를 신중하게 검토해 주세요.</mark><br/><br/> <b>인접한 진술문의 위치를 교환</b>하려면 진술문 오른쪽 또는 왼쪽의 위아래 화살표를 누르세요.<br/><br/><b>분리된 진술문의 위치를 교환</b>하려면 두 개의 진술문을 누르면(진술문 색상이 노란색으로 변경됨) 교환 확인 메시지가 나타납니다.<br/><br/>모든 순위에 만족하시면 오른쪽 하단의 탐색 버튼을 누르세요.`,
    mobileSortScrollBottomModalHead: `탐색 비활성화`,
    mobileSortScrollBottomModalText: `다음 단계로 이동하기 전에 맨 아래로 스크롤하여 모든 진술문의 순위를 검토해 주세요.`,
    postsortHeader: `분류 후 코멘트`,
    postsortInstructions: `<h3>이러한 진술문에 대한 귀하의 생각을 더 자세히 설명해 주세요.</h3>`,
    placeholder: `코멘트를 추가하려면 여기를 클릭하세요`,
    postsortPlacedOn: `배치 위치: `,
    postsortAgreement: `동의에 배치`,
    postsortDisagreement: `동의하지 않음에 배치`,
    postsortModalHead: `4단계 / 5단계`,
    postsortModalText: `페이지 하단의 버튼을 사용하여 글꼴 크기나 카드 높이를 변경할 수 있습니다.<br/>`,
    postsortPreventNavModalHead: `탐색 비활성화`,
    postsortPreventNavModalText: `다음 단계로 이동하기 전에 모든 카드에 코멘트를 추가해 주세요.`,
    postsortBackButtonText: `뒤로 가기`,
    mobilePostsortPreventNavModalHead: `탐색 비활성화`,
    mobilePostsortPreventNavModalText: `다음 단계로 이동하기 전에 모든 진술문에 코멘트를 추가해 주세요.`,
    mobilePostsortSortbarText: `분류 후 코멘트`,
    mobilePostsortPlaceholder: `코멘트를 추가하려면 여기를 클릭하세요`,
    mobilePostsortHelpModalHead: `4단계 / 5단계<br/> 순위 후 코멘트`,
    mobilePostsortHelpModalText: `이러한 진술문의 순위에 대해 코멘트해 주세요.`,
    surveyHeader: `분류 후 설문조사`,
    surveyModalHead: `5단계 / 5단계`,
    surveyModalText: `마지막으로, 귀하의 배경에 관한 다음 질문에 답변해 주세요. 제목에 "*"가 표시된 질문은 필수입니다.<br/>`,
    surveyPreventNavModalHead: `탐색 비활성화`,
    surveyPreventNavModalText: `다음 단계로 이동하기 전에 필수 질문(노란색으로 윤곽선 표시)에 답변해 주세요.`,
    mobileSurveyHelpModalHead: `5단계 / 5단계<br/> 순위 후 설문조사`,
    mobileSurveyHelpModalText: `이러한 배경 질문에 답변해 주세요.<br/><br/>일부 질문은 최종 단계로 이동하기 전에 답변을 제공해야 할 수 있습니다.`,
    btnTransfer: `데이터 제출`,
    transferHead: `최종 단계`,
    transferTextAbove: `<h1>제출 준비</h1><br/><br/> <h2>결과를 전송하려면 "데이터 제출" 버튼을 클릭해 주세요.</h2>`,
    transferTextBelow: `데이터가 서버로 성공적으로 전송되었음을 나타내는 확인 메시지를 기다려 주세요.`,
    transferOkModalHeader: `성공 - 데이터가 서버로 전송되었습니다.`,
    transferOkModalText: `Quince를 사용해 주셔서 감사합니다!<br/><br/>이제 브라우저 탭을 닫으실 수 있습니다.`,
    transferFailModalHeader: `서버 연결 실패`,
    transferFailModalText: `잠시 후에 다시 시도해 주세요.`,
    fallbackMessage: `*** 오류 - 전송 실패*** <br/><br/>인터넷 연결을 확인하고 "데이터 제출" 버튼을 다시 클릭해 주세요.`,
    btnDownload: `다운로드`,
    goodbyeMessage: `<div>감사합니다!</div> <br /><div>이제 브라우저 탭을 닫으실 수 있습니다</div>`,
    mobileSortTitleBar: `데이터 제출`,
    btnTransferEmail: `이메일 클라이언트를 열고 결과 보내기`,
    clipboardResults: `결과를 클립보드에 복사`,
    clipboardEmail: `이메일 주소를 클립보드에 복사`,
    copiedText: `복사됨!`,
    downloadResultsButtonText: `결과 다운로드`,
    copyFailMessage: `오류: 다시 시도해 주세요.`,
    defaultEmailClientFail:
      "기본 이메일 클라이언트가 이메일 본문에 결과와 함께 자동으로 열렸어야 합니다. 열리지 않았다면, 아래 버튼을 사용하여 정보를 복사하여 이메일에 붙여넣으세요.",
    emailBodyMessage:
      "이 이메일에 아무것도 추가할 필요가 없습니다. 보내기 버튼을 클릭하기만 하면 됩니다.",
    linkingFallbackMessage: "다음 Q 분류를 시작하려면 버튼을 클릭하세요",
    linkingBtnText: "다음 Q 분류 시작",
    localHeader: "오프라인 Q 분류 제어판",
    partIdText: "참여자 이름",
    usercodeText: "사용자 코드",
    localStartButtonText: "Q 분류 시작",
    localDeleteButtonText: "삭제",
    localDownloadButtonText: "Q 분류 데이터를 디스크에 저장",
    storedQsortsHeaderText: "저장된 Q 분류",
    localDeleteModalText:
      "이것은 현재 브라우저에 저장된 참여자 Q 분류 데이터를 삭제합니다. 일반적으로 새 프로젝트를 시작할 때만 이 작업을 수행합니다.<br/><br/><b>주의 - 삭제된 데이터는 복구할 수 없습니다.</b> <br/><br/> <center></center>",
    localDeleteModalHead: "브라우저에 저장된 데이터를 삭제하시겠습니까?",
    localParticipantsText: "참여자",
    localSaveDataButton: "참여자 데이터를 브라우저 메모리에 저장",
    localSubmitSuccessModalHeader: "성공",
    localSubmitSuccessModalText:
      "참여자 Q 분류 데이터가 브라우저 메모리에 성공적으로 저장되었습니다",
    localSaveBeforeDeleteModalHeader: "삭제 비활성화",
    localSaveBeforeDeleteModalText: "삭제하기 전에 Q 분류 데이터를 디스크에 저장하세요.",
    returnToLocalPanelButtonText: "제어판으로 돌아가기",
    emailSubjectText: `Quince Q-sort 결과`,
    submitFailMessage:
      "데이터베이스에 연결할 수 없습니다.<br/><br/>버튼을 클릭하여 기본 이메일 클라이언트를 열고 연구팀에 데이터가 포함된 이메일을 보내주세요.",
    checkInternetMessage:
      "*** 오류 - 전송 실패 ***<br/><br/>인터넷 연결을 확인하시고 '데이터 제출' 버튼을 다시 클릭해주세요.",
    press1: "(1번 누르기)",
    press2: "(2번 누르기)",
    press3: "(3번 누르기)",
  });
  return;
};

export { setLanguageSection_KO };
