import { useStore } from "../GlobalState/useStore.js";

const setLanguageSection_NL = (language) => {
  if (!language) {
    console.error("Language is not defined");
    return;
  }

  if (typeof language !== "string") {
    console.error("Language must be a string");
    return;
  }

  useStore.setState({
      btnHelp: "Help",
      fontSizeText: "Tekstgrootte",
      cardHeightText: "Kaardhoogte",
      btnNext: "Doorgaan",
      stepCompletedMessage: "U heeft deze stap voltooid. Klik op de <b>blauwe knop \"Doorgaan\"</b> rechtsonder op uw scherm om naar de volgende stap te gaan.",
      screenOrientationText: "Gebruik alstublieft de staande weergave!",
      mobileTextSize: "Tekst",
      mobileViewSize: "Weergave",
      mobileModalButtonCancel: "Annuleren",
      expandViewMessage: "Tik op de \"+ \" knop bij Weergave hieronder om het weergavegebied uit te breiden en dit bericht te verbergen.",
      consentTitleBarText: "Toestemming voor onderzoek",
      consentText: "U wordt uitgenodigd om deel te nemen aan een onderzoek uitgevoerd door [Naam hoofdonderzoeker] aan [Instelling of Organisatie]. Voordat u besluit om deel te nemen, is het belangrijk dat u begrijpt waarom het onderzoek wordt uitgevoerd en wat het zal inhouden. Neem alstublieft de tijd om de volgende informatie zorgvuldig te lezen. Neem gerust contact op met het onderzoeksteam als u vragen heeft.<br /><br /><b>Doel van het onderzoek</b><br />Het doel van dit onderzoek is om [beschrijf kort het doel, bijvoorbeeld: de effecten van een nieuwe onderwijsmethode op de prestaties van studenten te begrijpen]. Dit onderzoek zal ons helpen inzicht te krijgen in [vermeld bredere implicaties of doelen van het onderzoek]. <br /><br /><b>Onderzoeksprocedures</b><br />Als u ermee instemt om deel te nemen, wordt u gevraagd om [beschrijf de betrokken procedures, inclusief wat deelnemers zullen doen, hoe lang het zal duren en hoe vaak het zal plaatsvinden]. U wordt bijvoorbeeld gevraagd om een reeks uitspraken te evalueren, te sorteren en vervolgens te reflecteren op het sorteren. Daarnaast is er aan het eind een korte vragenlijst. Het onderzoek zal ongeveer [duur, bijvoorbeeld: 45 minuten] duren. <br /><br /><b>Voordelen</b><br />Hoewel er mogelijk geen directe voordelen voor u zijn door deelname, kan de informatie die in dit onderzoek wordt verzameld helpen om [beschrijf mogelijke voordelen, bijvoorbeeld: onderwijsmethoden te verbeteren, bij te dragen aan wetenschappelijke kennis, enz.]. U kunt ook persoonlijk inzicht krijgen in [beschrijf eventuele persoonlijke voordelen, indien van toepassing].<br /><br /><b>Vertrouwelijkheid</b><br />Alle informatie die in dit onderzoek wordt verzameld, wordt strikt vertrouwelijk behandeld. Gegevens worden veilig opgeslagen en alleen het onderzoeksteam heeft er toegang toe. Uw identiteit zal niet worden onthuld in rapporten of publicaties die uit dit onderzoek voortvloeien. [Beschrijf hoe gegevens geanonimiseerd, versleuteld of veilig worden opgeslagen].<br /><br /><b>Vrijwillige deelname</b><br />Uw deelname aan dit onderzoek is geheel vrijwillig. U bent vrij om deelname te weigeren of op elk moment te stoppen, zonder boete of verlies van voordelen waarop u anders recht heeft. Als u besluit om te stoppen, sluit de webpagina en alle tot dat moment verzamelde gegevens zullen worden verwijderd.<br /><br /><b>Toestemming</b><br />Door te klikken op de knop \"Akkoord\" onderaan deze pagina, geeft u aan dat u de verstrekte informatie heeft gelezen en begrepen, en dat u ermee instemt om deel te nemen aan dit onderzoek. Als u vragen heeft over dit onderzoek, neem dan contact op met [Naam en contactgegevens hoofdonderzoeker].",
      consentHelpModalHead: "Contactinformatie",
      consentHelpModalText: "Bedankt voor uw deelname aan dit universitaire onderzoeksproject. U kunt contact opnemen met het onderzoeksteam per telefoon (1-555-867-5309) of per e-mail op researchTeam@myMail.com",
      btnHelpConsent: "Contactinformatie",
      btnNextConsent: "Akkoord en doorgaan",
      loginWelcomeText: "<center></center><h3>Welkom!</h3></center><br/> Bedankt voor uw deelname aan dit Q-methodologie onderzoeksproject. <br/>Gelieve u <b>aan te melden</b> met behulp van het onderstaande formulier om het proces te beginnen. ",
      loginHeaderText: "Aanmelden",
      loginPartIdText: "Voer alstublieft uw naam of deelnemer-ID in",
      accessCodeText: "Toegangscode",
      accessInputText: "Voer alstublieft de toegangscode voor deze enquête in.",
      partIdWarning: "Ongeldige naam of ID",
      accessCodeWarning: "Toegangscode ongeldig",
      loginSubmitButtonText: "Verzenden",
      landingHead: "Universitair onderzoeksproject",
      welcomeText: "<h2>Quince Demoproject - iPad-gebruik in de klas.</h2><br/><br/><p>Bedankt voor uw hulp bij dit onderzoeksproject</p><br/>",
      landingHelpModalHead: "Welkom!",
      landingHelpModalText: "Bedankt voor uw deelname aan dit universitaire onderzoeksproject. Klik op de \"<b>Doorgaan</b>\" knop rechtsonder op het scherm om naar de volgende stap te gaan.",
      btnNextLanding: "Doorgaan",
      btnHelpLanding: "Help",
      mobileWelcomeText: "<h2>Quince Demoproject - iPad-gebruik in de klas.</h2><br/><br/><p>Bedankt voor uw hulp bij dit onderzoeksproject!</p><br/>",
      logInFirst: "Voltooi eerst het aanmeldproces.",
      titleBarText: "Voorlopige sortering",
      presortAgreement: "Eens (3)",
      presortNeutral: "Geen sterke gevoelens (2)",
      presortDisagreement: "Oneens (1)",
      presortStatements: "Uitspraken",
      presortModalHead: "Stap 1 van 4",
      presortModalText: "Lees de volgende uitspraken zorgvuldig en verdeel ze in drie stapels: een stapel voor uitspraken waarmee u het over het algemeen oneens bent, een stapel voor kaarten waarmee u het over het algemeen eens bent, en een stapel voor de rest. Wijzigingen kunnen later worden aangebracht.<br/><br/>Als u deze instructie een tweede keer wilt lezen, klik dan op de help-knop linksonder.<br/>",
      presortPreventNavModalHead: "Navigatie uitgeschakeld",
      presortPreventNavModalText: "Voltooi de voorlopige sortering voordat u naar de volgende stap gaat.",
      presortFinishedModalHead: "Voorlopige sortering voltooid",
      presortFinishedModalText: "U heeft deze stap voltooid. Klik op de knop \"Doorgaan\" rechtsonder op de pagina om naar de volgende stap te gaan.",
      presortOnPageInstructions: "<div style=\"font-size: 24px\">Klik en sleep op de kaarten of druk op de toetsen \"1\", \"2\" of \"3\" om de uitspraken te sorteren.</div>",
      presortImageSortInstructions: "Om een afbeelding te vergroten, beweeg uw muisaanwijzer erover en dubbelklik. <br/><br/> Om afbeeldingen te vergelijken, <u>druk en houd</u> de <b><i>Shift</i></b> toets op uw toetsenbord ingedrukt en dubbelklik vervolgens met uw muis op TWEE afbeeldingen.",
      mobilePresortConditionsOfInstruction: "Evalueer de uitspraken volgens uw ervaring met het gebruik van de iPads in de klas",
      mobilePresortCompletedLabel: "Voltooide evaluaties",
      mobilePresortAssignLeft: "Verschilt van mijn perspectief",
      mobilePresortAssignRight: "Vergelijkbaar met mijn perspectief",
      mobilePresortRedoModalHead: "Uitspraak opnieuw evalueren",
      mobilePresortRedoModalText: "Klik op het juiste pictogram",
      mobilePresortRedoModalConfirmButton: "Bevestigen",
      mobilePresortEvaluationsComplete: "<div><b>Alle uitspraken geëvalueerd.</b> <br /><br />Bekijk de uitspraken om uw evaluaties te bevestigen.  <br /><br /><div>",
      mobilePresortHelpModalHead: "Fase 1 van 5<br />Evaluatie van uitspraken",
      mobilePresortHelpModalText: "Tik op de juiste knop om een waarde aan elke uitspraak toe te kennen. <br /><br /> Als u het gevoel heeft dat de uitspraak <b>vergelijkbaar is met uw perspectief</b>, tik dan op de groene \"+\" knop.<br /><br /> Als u het gevoel heeft dat de uitspraak <b>verschilt van uw perspectief</b>, tik dan op de rode \"-\" knop. <br /><br />Als u onzeker bent, tik dan op de \"?\" knop. <br /><br /> Er zijn <b>33 uitspraken</b> in deze enquête. <br /><br /> Als u uw evaluatie wilt <b>wijzigen</b>, tik dan op het <b>opnieuw-pictogram</b> naast de uitspraak.",
      mobilePresortFinishedModalHead: "Fase 1 van 5<br />Evaluatie van uitspraken",
      mobilePresortFinishedModalText: "Het evaluatieproces is voltooid. <br/><br/> <b>Bekijk de uitspraken</b> om uw evaluaties te bevestigen.  <br /><br />Als u een wijziging wilt aanbrengen, tik dan op het \"opnieuw\" pictogram links van de uitspraak.<br /><br />Wanneer u tevreden bent met al uw evaluaties, tik dan op de <b>navigatieknop</b> rechtsonder.",
      mobilePresortProcessCompleteMessage: "Het evaluatieproces is voltooid. <br/><br/> Klik op de navigatieknop rechtsonder om naar de volgende fase te gaan.",
      mobilePresortPreventNavModalHead: "Navigatie uitgeschakeld",
      mobilePresortPreventNavModalText: "Voltooi de evaluaties voordat u naar de volgende fase gaat.",
      thinPageTitle: "Verfijn uw evaluaties",
      thinPageSubmitButton: "Verzenden",
      numStatementsToSelect: "Aantal te selecteren uitspraken",
      currentlySelectedNumber: "Huidig aantal geselecteerde uitspraken",
      thinningPreventNavModalHead: "Navigatie uitgeschakeld",
      thinningPreventNavModalText: "Voltooi het verfijningsproces voordat u naar de volgende stap gaat.",
      thinningHelpModalHead: "Verfijn uw evaluaties",
      thinningHelpModalText: "Bekijk nogmaals de uitspraken die u in de vorige fase heeft geëvalueerd. Kies degenen waarvan u vindt dat ze de beste uitdrukking zijn van uw perspectief.",
      thinningConfirmModalHead: "Onvolledige selectie",
      thinningConfirmModalText: "Selecteer het vereiste aantal uitspraken.",
      initialInstructionPart1: "Hieronder staan de uitspraken die u in de vorige stap positief heeft beoordeeld. Kies nu het aantal uitspraken waarmee u het <b>MEEST EENS</b> bent.<br /><br />",
      initialInstructionPart2: "Selecteer vervolgens de uitspraken die het DICHTST bij uw perspectief liggen",
      initialInstructionPart3: "Een nieuwe reeks uitspraken verschijnt op het scherm nadat u op de oranje knop \"Verzenden\" heeft geklikt.",
      initialInstructionPartNeg1: "Hieronder staan de uitspraken die u in de vorige stap positief heeft beoordeeld. Kies nu uitspraken die <mark><b>HET MEEST VERSCHILLEN VAN UW PERSPECTIEF</b></mark>.",
      initialInstructionPartNeg2: "Selecteer vervolgens de uitspraken die <mark>HET MEEST VERSCHILLEN</mark> van uw perspectief.",
      finalInstructions: "Verfijningsproces voltooid. Klik op de navigatieknop rechtsonder om naar de volgende fase te gaan.",
      moveTopMobileHead: "Bevestig verplaatsing",
      moveAllTopMobileText: "Alle geselecteerde uitspraken naar de bovenkant van de lijst verplaatsen?",
      moveTopMobileButtonOK: "Ja",
      mobileModalButtonCancel: "Annuleren",
      mobileThinConditionsOfInstruction: "Verfijn uw evaluaties",
      mobileThinSubmitButtonText: "Verzenden",
      mobileThinSelectedText: "Geselecteerd",
      mobileThinHelpModalHead: "Stap 2 van 5<br/>Verfijningsproces",
      mobileThinHelpModalText: "Tijdens deze fase wordt u gevraagd om de uitspraken die u heeft geëvalueerd <b>te bekijken</b> en degenen te kiezen die het meest vergelijkbaar zijn met of het meest verschillen van uw perspectief.<br/><br/>Mogelijk moet u <b>naar beneden scrollen</b> om alle uitspraken te zien.<br/><br/>Om <b>een uitspraak te selecteren</b>, tik op de container van de uitspraak. De kleur van de uitspraak verandert in geel.<br/><br/>Wanneer u het <b>juiste aantal</b> uitspraken heeft geselecteerd, verandert de knop \"Verzenden\" in <b>blauw</b>. <br/><br/>Om het vergelijken van de uitspraken gemakkelijker te maken, kunt u ze <b>opnieuw ordenen</b> door te tikken op de pijlen omhoog en omlaag aan de rechter- of linkerkant van de uitspraak.<br/><br/>U kunt ook <b>een groep</b> geselecteerde uitspraken naar de bovenkant van de lijst verplaatsen door <b>lang te drukken</b> (ongeveer 1 seconde) op de pijlen rechts van een uitspraak.",
      mobileThinPreventNavModalHead: "Navigatie uitgeschakeld",
      mobileThinPreventNavModalText: "Voltooi het verfijningsproces voordat u naar de volgende pagina navigeert.",
      mobileThinProcessCompleteMessage: "Het verfijningsproces is voltooid. <br/><br/> Klik op de navigatieknop rechtsonder om naar de volgende fase te gaan.",
      mobileGuidanceModalRight1Header: "Fase 2 van 5<br/> Verfijningsproces",
      mobileGuidanceModalRight1Text: "Er zijn verschillende stappen in deze fase. <br/><br/>Stap 1. Bekijk alle uitspraken die u <b>positief</b> heeft geëvalueerd en selecteer degenen die <b>het dichtst bij uw perspectief</b> liggen.<br/><br/>Mogelijk moet u <b>naar beneden scrollen</b> om alle uitspraken te zien.",
      mobileGuidanceModalRight2Header: "Fase 2 van 5<br/> Verfijningsproces",
      mobileGuidanceModalRight2Text: "Bekijk vervolgens opnieuw de resterende uitspraken die u <b>positief</b> heeft geëvalueerd en selecteer de <b>volgende set</b> uitspraken die <b>het dichtst bij uw perspectief</b> liggen.",
      mobileGuidanceModalLeft1Header: "Fase 2 van 5<br/> Verfijningsproces",
      mobileGuidanceModalLeft1Text: "Stap 2. Bekijk vervolgens alle uitspraken die u negatief heeft geëvalueerd en <b>selecteer</b> degenen die <b>het meest verschillen</b> van uw perspectief.<br/><br/>Mogelijk moet u <b>naar beneden scrollen</b> om alle uitspraken te zien.",
      mobileGuidanceModalLeft2Header: "Fase 2 van 5<br/> Verfijningsproces",
      mobileGuidanceModalLeft2Text: "Bekijk vervolgens opnieuw de resterende uitspraken die u <b>negatief</b> heeft geëvalueerd en <b>selecteer</b> de <b>volgende set</b> uitspraken die <b>het meest verschillen van uw perspectief</b>.",
      mobileThinScrollBottomModalHead: "Bevestiging uitgeschakeld",
      mobileThinScrollBottomModalText: "Scroll naar beneden en bekijk alle uitspraken voordat u uw selecties bevestigt.",
      sortHelpModalHead: "Stap 3 van 5",
      sortHelpModalText: "Klik en sleep in deze stap de uitspraakkaarten naar de juiste kolom op basis van uw perspectief en de instructies van de onderzoeker bovenaan de pagina. <br/>",
      sortAgreement: "Eens",
      sortDisagreement: "Oneens",
      condOfInst: "Sorteer de kaarten volgens uw ervaring met de iPads dit semester",
      sortingCompleteModalHead: "Sortering voltooid",
      sortingCompleteModalText: "U heeft de initiële sortering voltooid. Neem een moment om de plaatsing van de kaarten te bevestigen.<br/><br/>Wanneer u tevreden bent met hun plaatsing, klik dan op de <b>blauwe knop \"Doorgaan\"</b> rechtsonder op uw scherm om naar de volgende stap te gaan.",
      sortPreventNavModalHead: "Navigatie uitgeschakeld",
      sortPreventNavModalText: "Voltooi de rastersortering voordat u naar de volgende stap gaat.",
      sortOverloadedColumnModalHead: "Navigatie uitgeschakeld",
      sortOverloadedColumnModalText: "Een van de kolommen heeft te veel kaarten (deze wordt omlijnd in oranje en heeft een gestreepte rand). Pas de plaatsing van de kaarten aan zodat alle kolommen het juiste aantal hebben.",
      mobileSortSwapModalHead: "Rankings van uitspraken verwisselen?",
      mobileSortSwapModalSuccessMessage: "De posities van de uitspraken zijn succesvol verwisseld.",
      mobileSortSwapModalText: "Klik op \"Bevestigen\" om te verwisselen.",
      mobileSortSwapModalConfirmButton: "Verwisselen",
      mobileSortConditionsOfInstruction: "Rangschik de uitspraken volgens uw ervaring met het gebruik van de iPads in de klas",
      mobileSortHelpModalHead: "Fase 3 van 5<br/> Definitieve rangschikking van uitspraken",
      mobileSortHelpModalText: "De uitspraken zijn gerangschikt op basis van uw eerdere evaluaties.<br/><br/> Die uitspraken die het dichtst bij uw perspectief liggen, moeten bovenaan de lijst staan. Die het verst van uw perspectief verwijderd zijn, moeten onderaan de lijst staan.<br/><br/>U moet <b>naar beneden scrollen</b> om alle uitspraken te zien.<br/><br/>Gelieve de rangschikkingen te <b>bekijken</b> en eventuele noodzakelijke wijzigingen aan te brengen in de rangschikking van de uitspraken zodat de volgorde <b>uw perspectief nauwkeurig weerspiegelt</b>. <br/><br/><mark>Dit is de meest kritieke fase van de enquête, dus bekijk de rangschikkingen van de uitspraken zorgvuldig.</mark><br/><br/> Om <b>de posities van naburige uitspraken te verwisselen</b>, tik op de pijlen omhoog of omlaag aan de rechter- of linkerkant van de uitspraak.<br/><br/>Om <b>de posities van uitspraken die gescheiden zijn te verwisselen</b>, tik op twee uitspraken (de kleur van de uitspraak verandert in geel) en er verschijnt een bevestigingsbericht voor verwisseling.<br/><br/>Wanneer u tevreden bent met alle rangschikkingen, tik dan op de navigatieknop rechtsonder.",
      mobileSortScrollBottomModalHead: "Navigatie uitgeschakeld",
      mobileSortScrollBottomModalText: "Scroll naar beneden en bekijk de rangschikking van alle uitspraken voordat u naar de volgende fase gaat.",
      postsortHeader: "Opmerkingen na sortering",
      postsortInstructions: "<h3>Beschrijf alstublieft uw gedachten over deze uitspraken in meer detail.</h3>",
      placeholder: "Klik hier om een opmerking toe te voegen",
      postsortPlacedOn: "Geplaatst op ",
      postsortAgreement: "Geplaatst op Eens",
      postsortDisagreement: "Geplaatst op Oneens",
      postsortModalHead: "Stap 4 van 5",
      postsortModalText: "U kunt de knoppen onderaan de pagina gebruiken om de lettergrootte of kaardhoogte te wijzigen.<br/>",
      postsortPreventNavModalHead: "Navigatie uitgeschakeld",
      postsortPreventNavModalText: "Voeg opmerkingen toe aan alle kaarten voordat u naar de volgende stap gaat.",
      postsortBackButtonText: "Ga terug",
      mobilePostsortPreventNavModalHead: "Navigatie uitgeschakeld",
      mobilePostsortPreventNavModalText: "Voeg opmerkingen toe aan alle uitspraken voordat u naar de volgende stap gaat.",
      mobilePostsortSortbarText: "Opmerkingen na sortering",
      mobilePostsortPlaceholder: "Klik hier om een opmerking toe te voegen",
      mobilePostsortHelpModalHead: "Fase 4 van 5<br/> Opmerkingen na rangschikking",
      mobilePostsortHelpModalText: "Gelieve commentaar te geven op uw rangschikkingen van deze uitspraken.",
      surveyHeader: "Vragenlijst na sortering",
      surveyModalHead: "Stap 5 van 5",
      surveyModalText: "Beantwoord ten slotte de volgende vragen met betrekking tot uw achtergrond. De vragen die gemarkeerd zijn met een \"*\" in hun titel zijn verplicht.<br/>",
      surveyPreventNavModalHead: "Navigatie uitgeschakeld",
      surveyPreventNavModalText: "Beantwoord de verplichte vragen (omlijnd in geel) voordat u naar de volgende stap gaat.",
      mobileSurveyHelpModalHead: "Fase 5 van 5<br/> Enquête na rangschikking",
      mobileSurveyHelpModalText: "Beantwoord deze achtergrondvragen.<br/><br/>Sommige vragen vereisen mogelijk dat u een antwoord geeft voordat u naar de laatste stap kunt gaan.",
      btnTransfer: "Gegevens verzenden",
      transferHead: "Laatste stap",
      transferTextAbove: "<h1>Klaar om te verzenden</h1><br/><br/> <h2>Klik op de knop \"Gegevens verzenden\" om uw resultaten te verzenden.</h2>",
      transferTextBelow: "Wacht op het bevestigingsbericht dat aangeeft dat uw gegevens succesvol naar de server zijn verzonden.",
      transferOkModalHeader: "Succes - De gegevens zijn naar de server verzonden.",
      transferOkModalText: "Bedankt voor het gebruik van Quince!<br/><br/>U kunt nu uw browsertabblad sluiten.",
      transferFailModalHeader: "Verbinding met server mislukt",
      transferFailModalText: "Probeer het over een paar momenten opnieuw.",
      fallbackMessage: "*** Fout - Transmissiefout*** <br/><br/>Controleer uw internetverbinding en klik opnieuw op de knop \"Gegevens verzenden\".",
      btnDownload: "Downloaden",
      goodbyeMessage: "<div>Bedankt!</div> <br /><div>U kunt nu het browsertabblad sluiten</div>",
      mobileSortTitleBar: "Gegevens verzenden",
      btnTransferEmail: "Open e-mailclient en verzend resultaten",
      clipboardResults: "Kopieer resultaten naar klembord",
      clipboardEmail: "Kopieer e-mailadres naar klembord",
      copiedText: "Gekopieerd!",
      downloadResultsButtonText: "Download resultaten",
      copyFailMessage: "Fout: Probeer het opnieuw.",
      defaultEmailClientFail: "Uw standaard e-mailclient had automatisch moeten openen met de resultaten in de e-mailtekst. Als dit niet is gebeurd, gebruik dan de onderstaande knoppen om uw informatie te kopiëren en in een e-mail te plakken.",
      emailBodyMessage: "U hoeft niets aan deze e-mail toe te voegen. Klik gewoon op de knop VERZENDEN.",
      linkingFallbackMessage: "Klik op de knop om de volgende Q-sortering te beginnen",
      linkingBtnText: "Begin volgende Q-sortering",
      localHeader: "Offline Q-sortering configuratiescherm",
      partIdText: "Naam deelnemer",
      usercodeText: "Gebruikerscode",
      localStartButtonText: "Start Q-sortering",
      localDeleteButtonText: "Verwijderen",
      localDownloadButtonText: "Sla Q-sorteringsgegevens op naar schijf",
      storedQsortsHeaderText: "Opgeslagen Q-sorteringen",
      localDeleteModalText: "Dit verwijdert de Q-sorteringsgegevens van de deelnemer die momenteel in de browser zijn opgeslagen. U zou dit normaal gesproken alleen doen wanneer u een nieuw project start.<br/><br/><b>WAARSCHUWING - Verwijderde gegevens kunnen niet worden hersteld.</b> <br/><br/> <center></center>",
      localDeleteModalHead: "Gegevens opgeslagen in browser verwijderen?",
      localParticipantsText: "Deelnemers",
      localSaveDataButton: "Sla deelnemersgegevens op in browsergeheugen",
      localSubmitSuccessModalHeader: "Succes",
      localSubmitSuccessModalText: "Q-sorteringsgegevens van deelnemer zijn succesvol opgeslagen in browsergeheugen",
      localSaveBeforeDeleteModalHeader: "Verwijderen uitgeschakeld",
      localSaveBeforeDeleteModalText: "Sla Q-sorteringsgegevens op naar schijf voordat u ze verwijdert.",
      returnToLocalPanelButtonText: "Keer terug naar configuratiescherm",
      emailSubjectText: `Quince Q-sort resultaten`,
      submitFailMessage:
        "Kan geen verbinding maken met de database.<br/><br/>Klik op de knop om uw standaard e-mailprogramma te openen en een e-mail met de gegevens naar het onderzoeksteam te sturen.",
      checkInternetMessage:
        "*** Fout - Verzending mislukt ***<br/><br/>Controleer uw internetverbinding en klik opnieuw op de knop 'Gegevens verzenden'.",
      press1: "(druk 1)",
      press2: "(druk 2)",
      press3: "(druk 3)",
    });
  return;
};

export { setLanguageSection_NL };

