import { useStore } from "../GlobalState/useStore.js";

const setLanguageSection_IT = (language) => {
  if (!language) {
    console.error("Language is not defined");
    return;
  }

  if (typeof language !== "string") {
    console.error("Language must be a string");
    return;
  }

  useStore.setState({
    btnHelp: "Aiuto",
    fontSizeText: `Dimensione Testo`,
    cardHeightText: `Altezza Scheda`,
    btnNext: "Continua",
    stepCompletedMessage: `Hai completato questo passaggio. Fai clic sul <b>pulsante blu "Continua"</b> in basso a destra dello schermo per passare al passaggio successivo.`,
    screenOrientationText: `Si Prega di Utilizzare l'Orientamento Verticale!`,
    mobileTextSize: `Testo`,
    mobileViewSize: `Visualizza`,
    mobileModalButtonCancel: `Annulla`,
    expandViewMessage: `Tocca il pulsante "+" di Visualizza qui sotto per espandere l'area di visualizzazione e nascondere questo messaggio.`,
    consentTitleBarText: `Consenso alla Ricerca`,
    consentText: `Sei invitato a partecipare a uno studio di ricerca condotto da [Nome del Ricercatore Principale] presso [Istituzione o Organizzazione]. Prima di decidere se partecipare, è importante che tu comprenda perché la ricerca viene condotta e cosa comporterà. Si prega di prendersi il tempo necessario per leggere attentamente le seguenti informazioni. Non esitare a contattare il team di ricerca per qualsiasi domanda tu possa avere.<br /><br /><b>Scopo dello Studio</b><br />Lo scopo di questo studio è [descrivere brevemente lo scopo, ad es., comprendere gli effetti di un nuovo metodo di insegnamento sulle prestazioni degli studenti]. Questa ricerca ci aiuterà a ottenere informazioni su [menzionare eventuali implicazioni più ampie o obiettivi dello studio]. <br /><br /><b>Procedure dello Studio</b><br />Se accetti di partecipare, ti verrà chiesto di [descrivere le procedure coinvolte, incluso cosa faranno i partecipanti, quanto tempo ci vorrà e con quale frequenza si verificherà]. Ad esempio, ti verrà chiesto di completare la valutazione di una serie di affermazioni, ordinarle e poi riflettere sull'ordinamento. Inoltre, alla fine c'è un breve questionario. Lo studio richiederà circa [durata, ad es., 45 minuti]. <br /><br /><b>Benefici</b><br />Sebbene potrebbero non esserci benefici diretti per te nella partecipazione, le informazioni raccolte da questo studio potrebbero aiutare a [descrivere potenziali benefici, ad es., migliorare i metodi educativi, contribuire alla conoscenza scientifica, ecc.]. Potresti anche ottenere intuizioni personali su [descrivere eventuali benefici personali, se applicabile].<br /><br /><b>Riservatezza</b><br />Tutte le informazioni raccolte in questo studio saranno mantenute strettamente riservate. I dati saranno archiviati in modo sicuro e solo il team di ricerca vi avrà accesso. La tua identità non sarà divulgata in alcun rapporto o pubblicazione risultante da questo studio. [Descrivere come i dati saranno anonimizzati, crittografati o archiviati in modo sicuro].<br /><br /><b>Partecipazione Volontaria</b><br />La tua partecipazione a questo studio è del tutto volontaria. Sei libero di rifiutare di partecipare o di ritirarti in qualsiasi momento, senza penalità o perdita di benefici a cui hai altrimenti diritto. Se decidi di ritirarti, chiudi la pagina web e tutti i dati raccolti fino a quel momento saranno eliminati.<br /><br /><b>Consenso</b><br />Facendo clic sul pulsante "Accetto" nella parte inferiore di questa pagina, stai indicando di aver letto e compreso le informazioni fornite e di accettare di partecipare a questo studio. Se hai domande su questo studio, contatta [Nome e Informazioni di Contatto del Ricercatore Principale].`,
    consentHelpModalHead: `Informazioni di Contatto`,
    consentHelpModalText: `Grazie per aver partecipato a questo Progetto di Ricerca Universitaria. Puoi contattare il team di ricerca per telefono (1-555-867-5309) o via email all'indirizzo researchTeam@myMail.com`,
    btnHelpConsent: `Informazioni di Contatto`,
    btnNextConsent: `Accetto e Continua`,
    loginWelcomeText: `<center></center><h3>Benvenuto!</h3></center><br/> Grazie per aver partecipato a questo progetto di ricerca Q methodology. <br/>Si prega di <b>effettuare l'accesso</b> utilizzando il modulo sottostante per iniziare il processo. `,
    loginHeaderText: `Accedi`,
    loginPartIdText: `Inserisci il tuo nome o ID partecipante`,
    accessCodeText: `Codice di Accesso`,
    accessInputText: "Inserisci il codice di accesso per questo sondaggio.",
    partIdWarning: `Nome o ID non valido`,
    accessCodeWarning: `Codice di accesso non valido`,
    loginSubmitButtonText: `Invia`,
    landingHead: `Progetto di Ricerca Universitaria`,
    welcomeText: `<h2>Progetto Demo Quince - Uso dell'iPad in Classe.</h2><br/><br/><p>Grazie per aver collaborato a questo progetto di ricerca</p><br/><br/><br/> <center><iframe width="560" height="315" src="https://www.youtube.com/embed/lMy4ARVEcCI?rel=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></center>`,
    landingHelpModalHead: `Benvenuto!`,
    landingHelpModalText: `Grazie per aver partecipato a questo Progetto di Ricerca Universitaria. Fai clic sul pulsante "<b>Continua</b>" in basso a destra dello schermo per passare al passaggio successivo.`,
    btnNextLanding: `Continua`,
    btnHelpLanding: `Aiuto`,
    mobileWelcomeText: `<h2>Progetto Demo Quince - Uso dell'iPad in Classe.</h2><br/><br/><p>Grazie per aver collaborato a questo progetto di ricerca!</p><br/><br/><br/> <center><iframe width="560" height="315" src="https://www.youtube.com/embed/lMy4ARVEcCI?rel=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></center>`,
    logInFirst: "Completa prima il processo di accesso.",
    titleBarText: `Ordinamento Preliminare`,
    presortAgreement: `D'accordo (3)`,
    presortNeutral: `Nessun Forte Sentimento (2)`,
    presortDisagreement: `In Disaccordo (1)`,
    presortStatements: `Affermazioni`,
    presortModalHead: `Passaggio 1 di 4`,
    presortModalText: `Leggi attentamente le seguenti affermazioni e dividile in tre pile: una pila per le affermazioni con cui tendi a non essere d'accordo, una pila per le schede con cui tendi a essere d'accordo e una pila per il resto. Le modifiche possono essere apportate successivamente.<br/><br/>Se vuoi leggere questa istruzione una seconda volta, fai clic sul pulsante di aiuto nell'angolo in basso a sinistra.<br/><br/><center><iframe width="560" height="315" src="https://www.youtube.com/embed/vtnLuKzpcKQ?rel=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></center>`,
    presortPreventNavModalHead: `Navigazione Disabilitata`,
    presortPreventNavModalText: `Completa l'ordinamento preliminare prima di passare al passaggio successivo.`,
    presortFinishedModalHead: `Ordinamento Preliminare Completato`,
    presortFinishedModalText: `Hai completato questo passaggio. Fai clic sul pulsante "Continua" in basso a destra della pagina per passare al passaggio successivo.`,
    presortOnPageInstructions: `<div style="font-size: 24px">Fai clic e trascina sulle schede o premi i tasti "1", "2" o "3" per ordinare le affermazioni.</div>`,
    presortImageSortInstructions: `Per ingrandire un'immagine, posiziona il puntatore del mouse su di essa e fai doppio clic. <br/><br/> Per confrontare le immagini, <u>tieni premuto</u> il tasto <b><i>Shift</i></b> sulla tastiera e poi fai doppio clic su DUE immagini con il mouse.`,
    mobilePresortConditionsOfInstruction: `Valuta le Affermazioni in Base alla Tua Esperienza di Utilizzo degli iPad in Classe`,
    mobilePresortCompletedLabel: `Valutazioni Completate`,
    mobilePresortAssignLeft: `Diverso dalla Mia Prospettiva`,
    mobilePresortAssignRight: `Simile alla Mia Prospettiva`,
    mobilePresortRedoModalHead: `Rivaluta l'Affermazione`,
    mobilePresortRedoModalText: `Fai clic sull'icona appropriata`,
    mobilePresortRedoModalConfirmButton: `Conferma`,
    mobilePresortEvaluationsComplete: `<div><b>Tutte le Affermazioni Valutate.</b> <br /><br />Rivedi le affermazioni per confermare le tue valutazioni.  <br /><br /><div>`,
    mobilePresortHelpModalHead: `Fase 1 di 5<br />Valutazione delle Affermazioni`,
    mobilePresortHelpModalText: `Tocca il pulsante appropriato per assegnare un valore a ciascuna affermazione. <br /><br /> Se ritieni che l'affermazione sia <b>simile alla tua prospettiva</b>, tocca il pulsante verde "+". <br /><br /> Se ritieni che l'affermazione sia <b>diversa dalla tua prospettiva</b>, tocca il pulsante rosso "-". <br /><br />Se non sei sicuro, tocca il pulsante "?". <br /><br /> Ci sono <b>33 affermazioni</b> in questo sondaggio. <br /><br /> Se vuoi <b>modificare</b> la tua valutazione, tocca l'<b>icona rifai</b> accanto all'affermazione.`,
    mobilePresortFinishedModalHead: `Fase 1 di 5<br />Valutazione delle Affermazioni`,
    mobilePresortFinishedModalText: `Il processo di valutazione è completo. <br/><br/> <b>Rivedi le affermazioni</b> per confermare le tue valutazioni.  <br /><br />Se vuoi apportare una modifica, tocca l'icona "rifai" a sinistra dell'affermazione.<br /><br />Quando sei soddisfatto di tutte le tue valutazioni, tocca il <b>pulsante di navigazione</b> in basso a destra.`,
    mobilePresortProcessCompleteMessage: `Il processo di valutazione è completo. <br/><br/> Fai clic sul pulsante di navigazione in basso a destra per passare alla fase successiva.`,
    mobilePresortPreventNavModalHead: `Navigazione Disabilitata`,
    mobilePresortPreventNavModalText: `Completa le valutazioni prima di passare alla fase successiva.`,
    thinPageTitle: `Perfeziona le Tue Valutazioni`,
    thinPageSubmitButton: `Invia`,
    numStatementsToSelect: `Numero di Affermazioni da Selezionare`,
    currentlySelectedNumber: `Numero Attuale di Affermazioni Selezionate`,
    thinningPreventNavModalHead: `Navigazione Disabilitata`,
    thinningPreventNavModalText: `Completa il processo di perfezionamento prima di passare al passaggio successivo.`,
    thinningHelpModalHead: `Perfeziona le Tue Valutazioni`,
    thinningHelpModalText: `Rivedi le affermazioni che hai valutato nella fase precedente. Scegli quelle che ritieni siano la migliore espressione della tua prospettiva.`,
    thinningConfirmModalHead: `Selezione Incompleta`,
    thinningConfirmModalText: `Seleziona il numero richiesto di affermazioni.`,
    initialInstructionPart1: `Di seguito sono riportate le affermazioni che hai valutato positivamente nel passaggio precedente. Ora, scegli il numero di affermazioni con cui <b>SEI PIÙ D'ACCORDO</b>.<br /><br />`,
    initialInstructionPart2: `Successivamente, continua a selezionare le affermazioni PIÙ VICINE alla tua prospettiva`,
    initialInstructionPart3: `Un'altra serie di affermazioni apparirà sullo schermo dopo aver fatto clic sul pulsante arancione "Invia".`,
    initialInstructionPartNeg1: `Di seguito sono riportate le affermazioni che hai valutato positivamente nel passaggio precedente. Ora, scegli le affermazioni che <mark><b>DIFFERISCONO MAGGIORMENTE DALLA TUA PROSPETTIVA</b></mark>.`,
    initialInstructionPartNeg2: `Successivamente, continua a selezionare le affermazioni che <mark>DIFFERISCONO MAGGIORMENTE</mark> dalla tua prospettiva.`,
    finalInstructions: `Processo di perfezionamento completato. Fai clic sul pulsante di navigazione in basso a destra per passare alla fase successiva.`,
    moveTopMobileHead: `Conferma Spostamento`,
    moveAllTopMobileText: `Spostare tutte le affermazioni selezionate in cima all'elenco?`,
    moveTopMobileButtonOK: `Sì`,
    mobileModalButtonCancel: `Annulla`,
    mobileThinConditionsOfInstruction: `Perfeziona le Tue Valutazioni`,
    mobileThinSubmitButtonText: `Invia`,
    mobileThinSelectedText: `Selezionato`,
    mobileThinHelpModalHead: `Passaggio 2 di 5<br/>Processo di Perfezionamento`,
    mobileThinHelpModalText: `Durante questa fase ti verrà chiesto di <b>rivedere le affermazioni</b> che hai valutato e scegliere quelle che sono più simili o più diverse dalla tua prospettiva.<br/><br/>Potrebbe essere necessario <b>scorrere verso il basso</b> per vedere tutte le affermazioni.<br/><br/>Per <b>selezionare un'affermazione</b>, tocca il contenitore dell'affermazione. Il colore dell'affermazione cambierà in giallo.<br/><br/>Quando hai selezionato il <b>numero corretto</b> di affermazioni, il pulsante "Invia" diventerà <b>blu</b>. <br/><br/>Per facilitare il confronto delle affermazioni, puoi <b>riordinarle</b> toccando le frecce su e giù situate sui lati destro o sinistro dell'affermazione.<br/><br/>Puoi anche <b>spostare un gruppo</b> di affermazioni selezionate in cima all'elenco <b>premendo a lungo</b> (circa 1 secondo) sulle frecce a destra di un'affermazione.`,
    mobileThinPreventNavModalHead: `Navigazione Disabilitata`,
    mobileThinPreventNavModalText: `Completa il processo di perfezionamento prima di passare al passaggio successivo.`,
    mobileThinProcessCompleteMessage: `Il processo di perfezionamento è completo. <br/><br/> Fai clic sul pulsante di navigazione in basso a destra per passare alla fase successiva.`,
    mobileGuidanceModalRight1Header: `Fase 2 di 5<br/> Processo di Perfezionamento`,
    mobileGuidanceModalRight1Text: `Ci sono diversi passaggi in questa Fase. <br/><br/>Passaggio 1. Guarda tutte le affermazioni che hai valutato <b>positivamente</b> e seleziona quelle che sono <b>più vicine alla tua prospettiva</b>.<br/><br/>Potrebbe essere necessario <b>scorrere</b> verso il basso per vedere tutte le affermazioni.`,
    mobileGuidanceModalRight2Header: `Fase 2 di 5<br/> Processo di Perfezionamento`,
    mobileGuidanceModalRight2Text: `Successivamente, guarda ancora una volta le restanti affermazioni che hai valutato <b>positivamente</b> e seleziona il <b>prossimo gruppo</b> di affermazioni che sono <b>più vicine alla tua prospettiva</b>.`,
    mobileGuidanceModalLeft1Header: `Fase 2 di 5<br/> Processo di Perfezionamento`,
    mobileGuidanceModalLeft1Text: `Passaggio 2. Successivamente, guarda tutte le affermazioni che hai valutato negativamente e <b>seleziona</b> quelle che <b>differiscono maggiormente</b> dalla tua prospettiva.<br/><br/>Potrebbe essere necessario <b>scorrere verso il basso</b> per vedere tutte le affermazioni.`,
    mobileGuidanceModalLeft2Header: `Fase 2 di 5<br/> Processo di Perfezionamento`,
    mobileGuidanceModalLeft2Text: `Successivamente, guarda ancora una volta le restanti affermazioni che hai valutato <b>negativamente</b> e <b>seleziona</b> il <b>prossimo gruppo</b> di affermazioni che sono <b>più diverse dalla tua prospettiva</b>.`,
    mobileThinScrollBottomModalHead: `Conferma Disabilitata`,
    mobileThinScrollBottomModalText: `Scorri fino in fondo e rivedi tutte le affermazioni prima di confermare le tue selezioni.`,
    sortHelpModalHead: `Passaggio 3 di 5`,
    sortHelpModalText: `In questo passaggio, fai clic e trascina le schede delle affermazioni nella colonna appropriata in base alla tua prospettiva e alle istruzioni del ricercatore nella parte superiore della pagina. <br/><br/><center><iframe width="560" height="315" src="https://www.youtube.com/embed/iRxC9Vv3dLo?rel=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></center>`,
    sortAgreement: `D'accordo`,
    sortDisagreement: `In Disaccordo`,
    condOfInst: `Ordina le schede in base alla tua esperienza con gli iPad in questo semestre`,
    sortingCompleteModalHead: `Ordinamento Completato`,
    sortingCompleteModalText: `Hai completato l'ordinamento iniziale. Prenditi un momento per confermare il posizionamento delle schede.<br/><br/>Quando sei soddisfatto del loro posizionamento, fai clic sul <b>pulsante blu "Continua"</b> in basso a destra dello schermo per passare al passaggio successivo.`,
    sortPreventNavModalHead: `Navigazione Disabilitata`,
    sortPreventNavModalText: `Completa l'ordinamento della griglia prima di passare al passaggio successivo.`,
    sortOverloadedColumnModalHead: `Navigazione Disabilitata`,
    sortOverloadedColumnModalText: `Una delle colonne ha troppe schede (sarà evidenziata in arancione e avrà un bordo tratteggiato). Regola il posizionamento delle schede in modo che tutte le colonne abbiano il numero corretto.`,
    mobileSortSwapModalHead: `Scambiare le Classifiche delle Affermazioni?`,
    mobileSortSwapModalSuccessMessage: "Le posizioni delle affermazioni sono state scambiate con successo.",
    mobileSortSwapModalText: `Fai clic su "Conferma" per scambiare.`,
    mobileSortSwapModalConfirmButton: `Scambia`,
    mobileSortConditionsOfInstruction: `Classifica le Affermazioni in Base alla Tua Esperienza di Utilizzo degli iPad in Classe`,
    mobileSortHelpModalHead: `Fase 3 di 5<br/> Classificazione Finale delle Affermazioni`,
    mobileSortHelpModalText: `Le affermazioni sono state classificate in base alle tue valutazioni precedenti.<br/><br/> Quelle affermazioni che sono più vicine alla tua prospettiva dovrebbero essere in cima all'elenco. Quelle che sono più lontane dalla tua prospettiva dovrebbero essere in fondo all'elenco.<br/><br/>Dovrai <b>scorrere verso il basso</b> per vedere tutte le affermazioni.<br/><br/><b>Rivedi le classifiche</b> e apporta le modifiche necessarie alla classificazione delle affermazioni in modo che l'ordine <b>rifletta accuratamente la tua prospettiva</b>. <br/><br/><mark>Questa è la fase più critica del sondaggio, quindi rivedi attentamente le classifiche delle affermazioni.</mark><br/><br/> Per <b>scambiare le posizioni di affermazioni vicine</b>, tocca le frecce su o giù sul lato destro o sinistro dell'affermazione.<br/><br/>Per <b>scambiare le posizioni di affermazioni che sono separate</b>, tocca due affermazioni (il colore dell'affermazione cambierà in giallo) e apparirà un messaggio di conferma dello scambio.<br/><br/>Quando sei soddisfatto di tutte le classifiche, tocca il pulsante di navigazione in basso a destra.`,
    mobileSortScrollBottomModalHead: `Navigazione Disabilitata`,
    mobileSortScrollBottomModalText: `Scorri fino in fondo e rivedi la classificazione di tutte le affermazioni prima di passare alla fase successiva.`,
    postsortHeader: `Commenti Post-Ordinamento`,
    postsortInstructions: `<h3>Descrivi i tuoi pensieri su queste affermazioni in modo più dettagliato.</h3>`,
    placeholder: `Fai clic qui per aggiungere un commento`,
    postsortPlacedOn: `Posizionato su `,
    postsortAgreement: `Posizionato su D'accordo`,
    postsortDisagreement: `Posizionato su In Disaccordo`,
    postsortModalHead: `Passaggio 4 di 5`,
    postsortModalText: `Puoi utilizzare i pulsanti nella parte inferiore della pagina per modificare la dimensione del carattere o l'altezza della scheda.<br/><br/><center><iframe width="560" height="315" src="https://www.youtube.com/embed/EFNlSiaEVVg?rel=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></h3></center>`,
    postsortPreventNavModalHead: `Navigazione Disabilitata`,
    postsortPreventNavModalText: `Aggiungi commenti a tutte le schede prima di passare al passaggio successivo.`,
    postsortBackButtonText: `Torna Indietro`,
    mobilePostsortPreventNavModalHead: `Navigazione Disabilitata`,
    mobilePostsortPreventNavModalText: `Aggiungi commenti a tutte le affermazioni prima di passare al passaggio successivo.`,
    mobilePostsortSortbarText: `Commenti Post-Ordinamento`,
    mobilePostsortPlaceholder: `Fai clic qui per aggiungere un commento`,
    mobilePostsortHelpModalHead: `Fase 4 di 5<br/> Commenti Post-Classificazione`,
    mobilePostsortHelpModalText: `Commenta le tue classifiche di queste affermazioni.`,
    surveyHeader: `Questionario Post-Ordinamento`,
    surveyModalHead: `Passaggio 5 di 5`,
    surveyModalText: `Infine, rispondi alle seguenti domande riguardanti il tuo background. Le domande contrassegnate con un "*" nel titolo sono obbligatorie.<br/><br/><center><iframe width="560" height="315" src="https://www.youtube.com/embed/68MHzgLn1zg?rel=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></center>`,
    surveyPreventNavModalHead: `Navigazione Disabilitata`,
    surveyPreventNavModalText: `Rispondi alle domande obbligatorie (evidenziate in giallo) prima di passare al passaggio successivo.`,
    mobileSurveyHelpModalHead: `Fase 5 di 5<br/> Sondaggio Post-Classificazione`,
    mobileSurveyHelpModalText: `Rispondi a queste domande di background.<br/><br/>Alcune domande potrebbero richiedere una risposta prima di poter passare al passaggio finale.`,
    btnTransfer: `Invia Dati`,
    transferHead: `Passaggio Finale`,
    transferTextAbove: `<h1>Pronto per Inviare</h1><br/><br/> <h2>Fai clic sul pulsante "Invia Dati" per trasmettere i tuoi risultati.</h2>`,
    transferTextBelow: `Attendi il messaggio di conferma che indica che i tuoi dati sono stati inviati al server con successo.`,
    transferOkModalHeader: `Successo - I dati sono stati inviati al server.`,
    transferOkModalText: `Grazie per aver utilizzato Quince!<br/><br/>Ora puoi chiudere la scheda del browser.`,
    transferFailModalHeader: `Connessione al server non riuscita`,
    transferFailModalText: `Riprova tra qualche istante.`,
    fallbackMessage: `*** Errore - Trasmissione Fallita*** <br/><br/>Controlla la tua connessione internet e fai clic nuovamente sul pulsante "Invia Dati".`,
    btnDownload: `Scarica`,
    goodbyeMessage: `<div>Grazie!</div> <br /><div>Ora puoi chiudere la scheda del browser</div>`,
    mobileSortTitleBar: `Invia Dati`,
    btnTransferEmail: "Apri Client Email e Invia Risultati",
    clipboardResults: "Copia Risultati negli Appunti",
    clipboardEmail: "Copia Indirizzo Email negli Appunti",
    copiedText: "Copiato!",
    downloadResultsButtonText: "Scarica Risultati",
    copyFailMessage: "Errore: Riprova.",
    defaultEmailClientFail:"Il tuo client email predefinito dovrebbe essersi aperto automaticamente con i risultati nel corpo dell'email. Se non è successo, utilizza i pulsanti qui sotto per copiare e incollare le tue informazioni in un'email.",
    emailBodyMessage:"Non devi aggiungere nulla a questa email. Fai semplicemente clic sul pulsante INVIA.",
    linkingFallbackMessage: "Fai clic sul pulsante per iniziare il prossimo Q sort",
    linkingBtnText: "Inizia Prossimo Q sort",
    localHeader: "Pannello di Controllo Q-sort Offline",
    partIdText: "Nome Partecipante",
    usercodeText: "Codice Utente",
    localStartButtonText: "Avvia Q-sort",
    localDeleteButtonText: "Elimina",
    localDownloadButtonText: "Salva Dati Q-sort su Disco",
    storedQsortsHeaderText: "Q-sort Archiviati",
    localDeleteModalText:"Questo eliminerà i dati del Q-sort del partecipante attualmente archiviati nel browser. Di solito lo faresti solo quando inizi un nuovo progetto.<br/><br/><b>ATTENZIONE - I dati eliminati non possono essere recuperati.</b> <br/><br/> <center></center>",
    localDeleteModalHead: "Eliminare i Dati Archiviati nel Browser?",
    localParticipantsText: "Partecipanti",
    localSaveDataButton: "Salva Dati Partecipante nella Memoria del Browser",
    localSubmitSuccessModalHeader: "Successo",
    localSubmitSuccessModalText:"I dati del Q sort del partecipante sono stati salvati con successo nella memoria del browser",
    localSaveBeforeDeleteModalHeader: "Eliminazione Disabilitata",
    localSaveBeforeDeleteModalText: "Salva i Dati Q sort su Disco prima di eliminarli.",
    returnToLocalPanelButtonText: "Torna al Pannello di Controllo",
  });
  return;
};

export { setLanguageSection_IT };
