const exportSurveyObject = () => {
  const surveyQuestionObject = {
    text: [
      `<b>1. Answer Required (not shown in image): </b>true`,
      `<b>2. Label: </b>Age*`,
      `<b>3. Note: </b>Please enter your year of birth (YYYY, eg. 1980).`,
      `<b>4. Options: </b> N/A`,
      `<b>5. Scale: </b> N/A`,
      `<b>6. Placeholder: </b> (** no input = no placeholder text **)`,
      `<b>7. Limit Answer Length: </b>true`,
      `<b>8. Answer Maximum Length: </b>4`,
      `<b>9. Answer Restricted to Numbers "0-9": </b>true`,
    ],
    textarea: [
      `<b>1. Answer Required (not shown in image): </b>false`,
      `<b>2. Label: </b>2. Describe your experience using the iPads in this class.`,
      `<b>3. Note: </b>Write as much as you want - no character limit.`,
      `<b>4. Options: </b> N/A`,
      `<b>5. Scale: </b> N/A`,
      `<b>6. Placeholder: </b>input comment here (** caution - no HTML pair tag formatting allowed for placeholders**)`,
      `<b>7. Limit Answer Length: </b>N/A`,
      `<b>8. Answer Maximum Length: </b>N/A`,
      `<b>9. Answer Restricted to Numbers "0-9": </b>N/A`,
    ],
    radio: [
      `<b>1. Answer Required (not shown in image): </b>false`,
      `<b>2. Label: </b>3. What is your expected graduation date?`,
      `<b>3. Note: </b>Based on your current course load`,
      `<b>4. Options: </b>Fall 2028;;;Spring 2029;;;Fall 2029;;;After 2029`,
      `<b>5. Scale: </b> N/A`,
      `<b>6. Placeholder: </b> N/A`,
      `<b>7. Limit Answer Length: </b>N/A`,
      `<b>8. Answer Maximum Length: </b>N/A`,
      `<b>9. Answer Restricted to Numbers "0-9": </b>N/A`,
    ],
    rating2: [
      `<b>1. Answer Required (not shown in image): </b>false`,
      `<b>2. Label: </b>10. Please respond to the following statements about the technology used in the class.`,
      `<b>3. Note: </b>Please provide a response for all of the statements`,
      `<b>4. Options: </b>I have used an iPad in class before.;;;I have used a notebook computer in class before.;;;I have used Moodle before.;;;I have used Quizlet before.`,
      `<b>5. Scale: </b>Yes;;;No`,
      `<b>6. Placeholder: </b> N/A`,
      `<b>7. Limit Answer Length: </b>N/A`,
      `<b>8. Answer Maximum Length: </b>N/A`,
      `<b>9. Answer Restricted to Numbers "0-9": </b>N/A`,
    ],
    rating5: [
      `<b>1. Answer Required (not shown in image): </b>false`,
      `<b>2. Label: </b> &lt;i&gt;11.</i> Please rate the following statements about iPad use in this class.&lt;/i&gt;`,
      `<b>3. Note: </b>Please provide a rating for all of the statements`,
      `<b>4. Options: </b>How would you rate the use of iPads in this class?;;;How would you rate this class overall?`,
      `<b>5. Scale: </b> N/A`,
      `<b>6. Placeholder: </b> N/A`,
      `<b>7. Limit Answer Length: </b>N/A`,
      `<b>8. Answer Maximum Length: </b>N/A`,
      `<b>9. Answer Restricted to Numbers "0-9": </b>N/A`,
    ],
    rating10: [
      `<b>1. Answer Required (not shown in image): </b>false`,
      `<b>2. Label: </b>&lt;b&gt;12. Please rate the following statements&lt;/b&gt;`,
      `<b>3. Note: </b>Please provide a rating for all of the statements`,
      `<b>4. Options: </b>How would you rate the use of the Socrative website in this class?;;;How would you rate the use of the Quizlet website in this class?;;;How would you rate the use of Moodle in this class;;;How would you rate the use of Edmodo in this class`,
      `<b>5. Scale: </b> N/A`,
      `<b>6. Placeholder: </b> N/A`,
      `<b>7. Limit Answer Length: </b>N/A`,
      `<b>8. Answer Maximum Length: </b>N/A`,
      `<b>9. Answer Restricted to Numbers "0-9": </b>N/A`,
    ],
    checkbox: [
      `<b>1. Answer Required (not shown in image): </b>false`,
      `<b>2. Label: </b>5. What kind of class do you prefer?`,
      `<b>3. Note: </b>You can select more than one option`,
      `<b>4. Options: </b>Lecture;;;Group Discussion;;;Active Learning`,
      `<b>5. Scale: </b> N/A`,
      `<b>6. Placeholder: </b> N/A`,
      `<b>7. Limit Answer Length: </b>N/A`,
      `<b>8. Answer Maximum Length: </b>N/A`,
      `<b>9. Answer Restricted to Numbers "0-9": </b>N/A`,
    ],
    select: [
      `<b>1. Answer Required (not shown in image): </b>false`,
      `<b>2. Label: </b>4. What is your program focus?`,
      `<b>3. Note: </b>You can select more than one option`,
      `<b>4. Options: </b>Global Studies;;;Linguistics;;;English Literature`,
      `<b>5. Scale: </b> N/A`,
      `<b>6. Placeholder: </b> N/A`,
      `<b>7. Limit Answer Length: </b>N/A`,
      `<b>8. Answer Maximum Length: </b>N/A`,
      `<b>9. Answer Restricted to Numbers "0-9": </b>N/A`,
    ],
    likert: [
      `<b>1. Answer Required (not shown in image): </b>false`,
      `<b>2. Label: </b>9. How often do you use an iPad in your daily life?`,
      `<b>3. Note: </b> N/A`,
      `<b>4. Options: </b> N/A`,
      `<b>5. Scale (provide 3-7 choices):</b> Never;;;Rarely;;;Occasionally;;;Frequently;;;Very Frequently`,
      `<b>6. Placeholder: </b> N/A`,
      `<b>7. Limit Answer Length: </b>N/A`,
      `<b>8. Answer Maximum Length: </b>N/A`,
      `<b>9. Answer Restricted to Numbers "0-9": </b>N/A`,
    ],
    information: [
      `<b>1. Answer Required (not shown in image): </b>N/A`,
      `<b>2. Label: </b>N/A`,
      `<b>3. Note: </b>All fields marked with an * are mandatory`,
      `<b>4. Options: </b> N/A`,
      `<b>5. Scale (provide 3-7 choices):</b> N/A`,
      `<b>6. Placeholder: </b> N/A`,
      `<b>7. Limit Answer Length: </b>N/A`,
      `<b>8. Answer Maximum Length: </b>N/A`,
      `<b>9. Answer Restricted to Numbers "0-9": </b>N/A`,
    ],
  };
  return surveyQuestionObject;
};

export { exportSurveyObject };
