const exportSurveyObject = () => {
  const surveyQuestionObject = {
    information: [
      `<b>1. Type:</b> Information`,
      `<b>2. Answer Required (not shown in image): </b>N/A`,
      `<b>3. Label: </b>N/A`,
      `<b>4. Note: </b>All fields marked with an * are mandatory`,
      `<b>5. Options: </b> N/A`,
      `<b>6. Scale (provide 3-7 choices):</b> N/A`,
      `<b>7. Other Input:</b> N/A`,
      `<b>8. Limit Answer Length: </b>N/A`,
      `<b>9. Answer Maximum Length: </b>N/A`,
      `<b>10. Answer Restricted to Numbers "0-9": </b>N/A`,
      `<b>11. Information Bar Background Color: </b>#fde047`,
    ],
    text: [
      `<b>1. Type:</b> Text`,
      `<b>2. Answer Required (not shown in image): </b>true`,
      `<b>3. Label: </b>Age*`,
      `<b>4. Note: </b>Please enter your year of birth (YYYY, eg. 1980).`,
      `<b>5. Options: </b> N/A`,
      `<b>6. Scale: </b> N/A`,
      `<b>7. Other Input:</b> N/A`,
      `<b>8. Limit Answer Length: </b>true`,
      `<b>9. Answer Maximum Length: </b>4`,
      `<b>10. Answer Restricted to Numbers "0-9": </b>true`,
      `<b>11. Information Bar Background Color: </b>N/A`,
    ],
    textarea: [
      `<b>1. Type:</b> Textarea`,
      `<b>2. Answer Required (not shown in image): </b>false`,
      `<b>3. Label: </b>2. Describe your experience using the iPads in this class.`,
      `<b>4. Note: </b>Write as much as you want - no character limit.`,
      `<b>5. Options: </b> N/A`,
      `<b>6. Scale: </b> N/A`,
      `<b>7. Other Input:</b> N/A`,
      `<b>8. Limit Answer Length: </b>N/A`,
      `<b>9. Answer Maximum Length: </b>N/A`,
      `<b>10. Answer Restricted to Numbers "0-9": </b>N/A`,
      `<b>11. Information Bar Background Color: </b>N/A`,
    ],
    radio: [
      `<b>1. Type:</b> Radio`,
      `<b>2. Answer Required (not shown in image): </b>false`,
      `<b>3. Label: </b>3. What is your expected graduation date?`,
      `<b>4. Note: </b>Based on your current course load`,
      `<b>5. Options: </b>Fall 2028<mark>;;;</mark>Spring 2029<mark>;;;</mark>Fall 2029<mark>;;;</mark>After 2029    (separate options with ;;;)`,
      `<b>6. Scale: </b> N/A`,
      `<b>7. Other Input:</b> true`,
      `<b>8. Limit Answer Length: </b>N/A`,
      `<b>9. Answer Maximum Length: </b>N/A`,
      `<b>10. Answer Restricted to Numbers "0-9": </b>N/A`,
      `<b>11. Information Bar Background Color: </b>N/A`,
    ],
    select: [
      `<b>1. Type:</b> Select`,
      `<b>2. Answer Required (not shown in image): </b>false`,
      `<b>3. Label: </b>4. What is your program focus?`,
      `<b>4. Note: </b>You can select more than one option`,
      `<b>5. Options: </b>Global Studies<mark>;;;</mark>Linguistics<mark>;;;</mark>English Literature`,
      `<b>6. Scale: </b> N/A`,
      `<b>7. Other Input:</b> N/A`,
      `<b>8. Limit Answer Length: </b>N/A`,
      `<b>9. Answer Maximum Length: </b>N/A`,
      `<b>10. Answer Restricted to Numbers "0-9": </b>N/A`,
      `<b>11. Information Bar Background Color: </b>N/A`,
    ],
    checkbox: [
      `<b>1. Type:</b> Checkbox`,
      `<b>2. Answer Required (not shown in image): </b>false`,
      `<b>3. Label: </b>5. What kind of class do you prefer?`,
      `<b>4. Note: </b>You can select more than one option`,
      `<b>5. Options: </b>Lecture<mark>;;;</mark>Group Discussion<mark>;;;</mark>Active Learning    (separate options with ;;;)`,
      `<b>6. Scale: </b> N/A`,
      `<b>7. Other Input:</b> true`,
      `<b>8. Limit Answer Length: </b>N/A`,
      `<b>9. Answer Maximum Length: </b>N/A`,
      `<b>10. Answer Restricted to Numbers "0-9": </b>N/A`,
      `<b>11. Information Bar Background Color: </b>N/A`,
    ],
    rating2: [
      `<b>1. Type:</b> Rating 2`,
      `<b>2. Answer Required (not shown in image): </b>false`,
      `<b>3. Label: </b>10. Please respond to the following statements about the technology used in the class.`,
      `<b>4. Note: </b>Please provide a response for all of the statements`,
      `<b>5. Options: </b>I have used an iPad in class before.<mark>;;;</mark>I have used a notebook computer in class before.<mark>;;;</mark>I have used Moodle before.<mark>;;;</mark>I have used Quizlet before.    (separate options with ;;;)`,
      `<b>6. Scale: </b>Yes<mark>;;;</mark>No     (separate scale labels with ;;;)`,
      `<b>7. Other Input:</b> N/A`,
      `<b>8. Limit Answer Length: </b>N/A`,
      `<b>9. Answer Maximum Length: </b>N/A`,
      `<b>10. Answer Restricted to Numbers "0-9": </b>N/A`,
      `<b>11. Information Bar Background Color: </b>N/A`,
    ],
    rating5: [
      `<b>1. Type:</b> Rating 5`,
      `<b>2. Answer Required (not shown in image): </b>false`,
      `<b>3. Label: </b> &lt;i&gt;11.</i> Please rate the following statements about iPad use in this class.&lt;/i&gt;`,
      `<b>4. Note: </b>Please provide a rating for all of the statements`,
      `<b>5. Options: </b>How would you rate the use of iPads in this class?;;;How would you rate this class overall?`,
      `<b>6. Scale: </b> N/A`,
      `<b>7. Other Input:</b> N/A`,
      `<b>8. Limit Answer Length: </b>N/A`,
      `<b>9. Answer Maximum Length: </b>N/A`,
      `<b>10. Answer Restricted to Numbers "0-9": </b>N/A`,
      `<b>11. Information Bar Background Color: </b>N/A`,
    ],
    rating10: [
      `<b>1. Type:</b> Rating 10`,
      `<b>2. Answer Required (not shown in image): </b>false`,
      `<b>3. Label: </b>&lt;b&gt;12. Please rate the following statements&lt;/b&gt;`,
      `<b>4. Note: </b>Please provide a rating for all of the statements`,
      `<b>5. Options: </b>How would you rate the use of the Socrative website in this class?;;;How would you rate the use of the Quizlet website in this class?;;;How would you rate the use of Moodle in this class;;;How would you rate the use of Edmodo in this class`,
      `<b>6. Scale: </b> N/A`,
      `<b>7. Other Input:</b> N/A`,
      `<b>8. Limit Answer Length: </b>N/A`,
      `<b>9. Answer Maximum Length: </b>N/A`,
      `<b>10. Answer Restricted to Numbers "0-9": </b>N/A`,
      `<b>11. Information Bar Background Color: </b>N/A`,
    ],
    likert: [
      `<b>1. Answer Required (not shown in image): </b>false`,
      `<b>2. Label: </b>9. How often do you use an iPad in your daily life?`,
      `<b>3. Note: </b> N/A`,
      `<b>4. Options: </b> N/A`,
      `<b>5. Scale (provide 3-7 choices):</b> Never;;;Rarely;;;Occasionally;;;Frequently;;;Very Frequently`,
      `<b>6. Placeholder: </b> N/A`,
      `<b>7. Other Input:</b> N/A`,
      `<b>8. Limit Answer Length: </b>N/A`,
      `<b>9. Answer Maximum Length: </b>N/A`,
      `<b>10. Answer Restricted to Numbers "0-9": </b>N/A`,
      `<b>11. Information Bar Background Color: </b>N/A`,
    ],
  };
  return surveyQuestionObject;
};

export { exportSurveyObject };
